rbac:
  enabled: true
images:
  actualizer:
    repository: 410240865662.dkr.ecr.us-west-2.amazonaws.com/actualizer
    tag: latest
    pullPolicy: Always
  eg:
    repository: 'expressgateway/express-gateway'
    tag: latest
  kubectl:
    repository: 410240865662.dkr.ecr.us-west-2.amazonaws.com/kubectl
    tag: 1.4.6
configStore:
  url: http://configstore.default/api
  sleepTime: 3000
versions:
  workspace: latest
  serverless: latest
adminOrigin: 'http://dev.lunchbadger.com'
customerDomain: lunchbadger.io
workspaceAPIURLTemplate: 'http://workspace-$PRODUCER-$ENV.customer:81/api'
serverlessAPIURLTemplate: 'http://sls-api-$PRODUCER-$ENV.customer'
debugPattern: "actualizer:*"
