name: dex
description: A CoreOS Dex chart for Kubernetes
version: v0.1.1
keywords: 
  - coreos
  - dex
  - auth
  - oidc
home: https://github.com/samsung-cnct/chart-dex
sources: 
  - https://github.com/coreos/dex.git
icon: https://davidewatson.github.io/k2/_static/k2.png
maintainers:
  - name: Chanhun Jeong
    email: keyolk@gmail.com
  - name: Joe Julian
    email: me@joejulian.name
engine: gotpl
