traefik:
  enabled: false
redis:
  enabled: false
prometheus:
  enabled: false
grafana:
  enabled: false
kubernetes-dashboard:
  enabled: false
gitea:
  enabled: false
kubeless:
  enabled: false
git-api:
  enabled: false
configstore:
  enabled: false
actualizer:
  enabled: false
kube-watcher:
  enabled: false
gateway:
  enabled: false
logging:
  enabled: false
graphql:
  enabled: false
mainIngress:
  enabled: false
customerNamespace:
  enabled: false
storageClassCeph:
  enabled: false
storageClass:
  enabled: false
  name: standard
  type: gp2
  zones: 'us-west-2a, us-west-2b'
  iopsPerGB: 10
storageClass2:
  enabled: false
  name: zonec
  type: gp2
  zones: us-west-2c
  iopsPerGB: 10
